services:
  teslacam-viewer:
    build: .
    image: ghcr.io/adsouza98/teslacam-viewer:1.4.6
    container_name: teslacam-viewer
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - AUTH_USER=${TESLACAM_AUTH_USER:-}
      - AUTH_PASS=${TESLACAM_AUTH_PASS:-}
    volumes:
      - ${TESLACAM_MEDIA_PATH:-./media}:/media:ro
      - teslacam-cache:/cache
    ports:
      - "${TESLACAM_PORT:-8000}:8000"
    restart: unless-stopped

volumes:
  teslacam-cache:
